### ISSUE TITLE
Still cached after username change

### ISSUE THREAD

**Issue by owldesign** [codemonauts/craft-instagram-feed#1]
I think the cache should be cleared if after someone updates username. After I changed, it still caches old account.

Also a cool feature would be to create ability to make multiple targets. For example I have a website with different categories of content and each might have a specific IG account I want to display posts from. 

Thanks!

**Comment by kringkaste** [comment]
Right, the cache should empty when the user changes. We'll fix that. 

The enhancement to be able to set the user when calling the function, we had already thought about that. We will implement it soon. Thanks for the feedback.

**Comment by dwhoban** [comment]
+1 for the ability to have multiple Instagram accounts.  Are you considering per-site configurations for this?  I am working on a website that has 3 sites, each with their own IG accounts.

**Comment by kringkaste** [comment]
With the new release 1.0.1 you can pass an account name when calling the function. We are also caching the results based on the account name now, so switching account names should not be a problem anymore.

A per site configuration requires an extra database table and its administration (because Craft don't support this now). I would like to avoid this in order to keep the complexity as low as possible.
