### ISSUE TITLE
Only pulls in the first 12 posts

### ISSUE THREAD

**Issue by tom-byrom** [codemonauts/craft-instagram-feed#11]
Hey any way for it to load more than 12 posts?

Can't see anything in the documentation

Thanks

**Comment by fleaz** [comment]
Hey,
currently this is not possible, sorry.

Due to the lack of an Instagram API we access the public profile page of a user ( `instagram.com/<username>`). This page contains only the first twelve images on the first load, more images get loaded via Javascript when you scroll down which our crawler code currently doesn't do. This is why we are capped at twelve at the moment.

Best,
Felix

**Comment by tom-byrom** [comment]
No worries - I assumed it was a API limitation! Thanks anyway
