### ISSUE TITLE
Feed not up to date

### ISSUE THREAD

**Issue by stefanmf** [codemonauts/craft-instagram-feed#21]
The feed I'm getting is not up to date per today, got this in the log:
`2019-10-10 09:44:41 [-][1][-][error][codemonauts\instagramfeed\services\InstagramService::getInstagramAccountData] Instagram profile data could not be fetched. Maybe the site structure has changed.`

**Comment by fleaz** [comment]
Hi @stefanmf,
this behaviour could have multiple reasons. Can you please upgrade the plugin to "dev-master" in your dependencies. This way you get the `dump` option in the config: https://github.com/codemonauts/craft-instagram-feed/blob/fb5b3d97755a7353bbe04789860d6ddfbff47d18/src/config.php#L14 

When `dump` is set, the plugin will write the response you get form Instagram to a file in `/runtime/instagramfeed`. When you provide this file to us, I can have a look and maybe we can find a solution.

Felix

**Comment by stefanmf** [comment]
The issue seems to have resolved itself, but I will try what you suggested if it resurfaces. Thanks a lot.
Stefan

**Comment by fleaz** [comment]
Okay, nice to hear that.

I will close this for now, but feel free to reopen it if the problem reoccurs :)

**Comment by fleaz** [comment]
Hey,

because multiple of our customers who use this plugin faced the same problem of beeing blacklisted by Instagram and therefore couldn't use our plugin, we started to implement a new feature which will circumvent this and use a proxy server to get the data.
If you still have this problem and wan't to give our plugin another chance, we would love to have you in our beta test for the next version.

Just write a mail to support@codemonauts.com and we will give you a beta key and all the details on how to use it :)

Best regards,
Felix
