### ISSUE TITLE
Possible to create feed of instagram photos from an account filtered by hashtag?

### ISSUE THREAD

**Issue by paragonn** [codemonauts/craft-instagram-feed#26]
I see that there are two options:
1. Create a feed from an Instagram account
2. Create a feed from a hashtag

However, it is possible to create a feed from an Instagram account that is filtered by a hashtag?

Thanks!

**Comment by fleaz** [comment]
Hi @paragonn 
this is currently not possible, sorry. This would also introduce the problem that you would probably get very few images:
Due to the way we access IG we don't get more than 12 images per profile or per hashtag. When we now would apply filtering to these images you would be left with something between zero and 12 images. This would probably not be beneficial.
