### ISSUE TITLE
No Response data

### ISSUE THREAD

**Issue by dennismeissner** [codemonauts/craft-instagram-feed#31]
Hey, 

today i noticed, that your plugin is no longer working. Our public account feeds remain empty.

i checked the logs:

```
[trace][codemonauts\instagramfeed\services\InstagramService::getFeed] Get feed for "@__PUBLIC_PROFILE__"
[trace][codemonauts\instagramfeed\services\InstagramService::getFeed] No cached data found, start fetching Instagram page.
[trace][codemonauts\instagramfeed\services\InstagramService::fetchInstagramPage] Using php file stream to fetch Instagram page.
[trace][codemonauts\instagramfeed\services\InstagramService::parseInstagramResponse] 
[error][codemonauts\instagramfeed\services\InstagramService::parseInstagramResponse] Unknown response from Instagram. Please check debug output in devMode.
[trace][codemonauts\instagramfeed\services\InstagramService::getFeed] Returning cached items.
```

I debugged a little into your plugin and it seems that fetching the feedpage doesn't return anything at the moment. Did Instagram change something with their restrictions?

**Comment by DidoMarchet** [comment]
Hi,
I've got (maybe) the same issue.
in production it doesn't return any feed
but, in my case,  it returns feeds correctly  in locale enviroment.

Have a nice day and thanks,
D.

**Comment by fleaz** [comment]
Hey @dennismeissner @DidoMarchet ,

I guess you both hit the same problem as #28 which is due to Instagrams "Bot Detection" where they block  everything which is a IP from a datacenter so the plugin works locally but not in production. We started to implement some kind of proxy server on our side which gets used by our plugin when you enable the right switch. Just drop us an email at support@codemonauts.com and I can give you the required config file and an access key to try out our proxy which should fix the problem for both of you :)

Best regards,
Felix
