### ISSUE TITLE
Change cache period to custom value

### ISSUE THREAD

**Issue by rowansentesy** [codemonauts/craft-instagram-feed#33]
I have installed this plugin on a client site and they have requested the 6hr default cache duration to be decreased. Is there any way to expose this parameter and set it in the config? 
I could not see any documentation indicating that this is possible. 

Thanks,
Rowan

**Comment by kringkaste** [comment]
Hi Rowan, no at the moment you cannot overwrite the default cache time. We have to protect our proxies from being blocked. We will change this in the next release coming soon.

**Comment by fleaz** [comment]
Hey,
after running the proxy for quite a while now we decided against a configurable cache duration. Quite a lot users rely on our proxy for their websites and this generates already a lot of requests which we need to handle. When making the cache duration configurable, everybody would immediately set this to an unnecessarily* small value to get their images as fast as possible which would increase the amount of requests by multiple magnitudes and would immediately get all our accounts blocked because IG is pretty sensitive to high request counts even when you are properly logged in.

And even if one would use our plugin without our proxy, decreasing this duration would just highly increase your chances of getting blocked and relying on the proxy in the long run.


Therefore I'm  going to close this issue now because implementing it would create more harm than benefit.


* IMHO will nobody (except the client itself) notice this because you would need to visit the website and the IG profile one after another and also remember what the most recent image was on both pages
