### ISSUE TITLE
Get usernames for hashtag feeds

### ISSUE THREAD

**Issue by CharlieGentle** [codemonauts/craft-instagram-feed#35]
Is it possible to get the username for posts when getting a feed based on hashtag?

**Comment by fleaz** [comment]
Hey @CharlieGentle 
no, this is currently not possible.

But this would indeed be a good feature so we added it to our todo list for the next release :) I guess most of our user use the plugin to request a user profile instead of a hashtag, therefore nobody found that this quite crucial information is missing *cough*

Thanks for the hint!

Best regards,
Felix

**Comment by garrill** [comment]
Has this been added to the plugin yet? It doesn't look like there is a username variable in the object

**Comment by kringkaste** [comment]
Hey! Sorry, but Instagram only returns the ID of the owner and not the username. So we cannot add the username to the object.
