### ISSUE TITLE
cURL error 28 -- using the proxy solution

### ISSUE THREAD

**Issue by boldenamsterdam** [codemonauts/craft-instagram-feed#43]
Hi Codemonauts, 

Since Saturday we have an issue with a website that makes use of the amazing proxy solution.
Loading of the website is completely blocked and is spitting out the following message:

`GuzzleHttp\Exception\ConnectException cURL error 28: Operation timed out after 5001 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)`

Looks like something is going wrong with the connection to the proxy server?
It stays in this loop with retrying and the rest of the website is not getting loaded.

If more info is needed please let us know

**Comment by TomDeSmet** [comment]
We have the same issue.

**Comment by fleaz** [comment]
Hey,

we sadly had some network issues over the weekend and the proxy was indeed not reachable. Because the timeout for our upstream servers was configured to high you also didn't got the cached version and instead received the timeout from the plugin.
Everything should be fixed since this morning :)

Sorry for the trouble!


Felix

**Comment by clarknelson** [comment]
I'm still getting the timeout message on my website 🤒

**Comment by clarknelson** [comment]
![image](https://user-images.githubusercontent.com/4106671/107530502-8e764180-6b81-11eb-8e52-11ac1d7681a2.png)

**Comment by fleaz** [comment]
Hey @clarknelson,
sorry to hear that you have problems with our plugin and the proxy.
I checked the logs and I can see multiple requests from you in the logs so the plugin is working and requests updates multiple times a day. We also have a fairly recent cached version of your profile at the caching layer in our proxy, so the response time should be <1-2s most of the time depending on your location. And because it's currently running fine (from what I can tell by visiting your page) I guess this was really some network problems because this request goes around the globe once.

But yes, the fact that a timeout crashes the site is far from perfect and we will fix this.

**Comment by clarknelson** [comment]
Thanks for the message! (and for handling our site's traffic 😅) I understand some network issues are unavoidable and it works most of the time. I just wanted to follow up and see what we could do, if there is any way this could be a 'soft' crash? Would reducing the refresh rate help?

**Comment by fleaz** [comment]
Depending on your webserver configuration, you could increase the guzzle timeout in the config from 5 to e.g. 15 seconds. The page will load slowly in such a case but you wont see the exception. And as soon as it got one successfull answer, your Craft has it cached and will be fast the next time.
But yes, catching this problem is on the roadmap for the next release.

**Comment by clarknelson** [comment]
Okay if you have something planned I will try to relax a little bit.. thank you so much :)

**Comment by fleaz** [comment]
Hey everyone,

we just released v1.0.6 which handles the guzzle exception and wont crash the whole page when the plugin encounters a timeout

**Comment by clarknelson** [comment]
Thank you so much 😭 all updated!

**Comment by boldenamsterdam** [comment]
Awesome, thanks!
