### ISSUE TITLE
Freshly installed plugin not working

### ISSUE THREAD

**Issue by Simon-00** [codemonauts/craft-instagram-feed#47]
Hey guys,

I tried out your plugin inside a freshly installed testing environment, just to see how the results are parsed.
Unfortunately I'm not able to get the plugin going. I feel like it's more a instagram structure change than a bug.

`2021-02-09 09:25:26 [-][1][-][error][codemonauts\instagramfeed\services\InstagramService::getInstagramAccountData] Instagram profile data could not be fetched. Maybe the site structure has changed.
2021-02-09 09:25:26 [-][1][-][trace][codemonauts\instagramfeed\services\InstagramService::getFeed] Returning cached items.
2021-02-09 09:25:26 [-][1][-][profile end][Twig template] render template: instagram
2021-02-09 09:25:25 [-][1][-][info][application] $_GET = [
    'p' => 'instagram'
]`

Can anyone else report about this error?

**Comment by fleaz** [comment]
Hey @Simon-00,
Instagram is blocking requests if they see they are coming from a server rather than a private internet connection to make it harder for e.g. bot accounts. Therefore our plugin reports `site structure has changed` because instead of the profile page the plugin requested, Instagram returns a redirect to the login page (to prove that we are not a bot).

Just have a look at #32 where I described the problem and how you can fix it :)

Felix
