### ISSUE TITLE
Failed to load resource: net::ERR_BLOCKED_BY_RESPONSE

### ISSUE THREAD

**Issue by Lohitapallanti** [codemonauts/craft-instagram-feed#51]
Instagramfeed was working fine until yesterday, since today it is showing Failed to load resource: net::ERR_BLOCKED_BY_RESPONSE this error in console in both local and production site.
<img width="1336" alt="Screenshot 2021-04-27 at 10 38 28" src="https://user-images.githubusercontent.com/40202055/116212046-ba4aa180-a744-11eb-97fc-f929e6d0dcad.png">

**Comment by fleaz** [comment]
Hey,

yes, we are already aware of this issue. Instagram changed their server configuration yesterday and now sets the "cross-origin-resource-policy" header to "same-origin" which means that your browser is not allowed to load the image inside another website which is not "instagram.com". We are already working on a new release to fix this. In the meantime there is sadly nothing you can do than disable this block in your site.

**Comment by iamtompickering** [comment]
I was just about to create a new issue about this. Getting the same errors on a site of mine. 

Just subscribed to this, so will wait to hear back about a new release to fix this!

**Comment by gdelorey** [comment]
Subscribing for an update

**Comment by bossanova808** [comment]
Subscribing for an update

**Comment by connorcowling** [comment]
Looking forward to the fix for this

**Comment by fleaz** [comment]
Hey everyone,

we just released version [1.1.1](https://github.com/codemonauts/craft-instagram-feed/releases/tag/1.1.1) which will fix this problem by downloading the images to your web server instead of loading the images directly from Instagram. Therefore please read the changelog of the new release! Especially if you are running multiple web servers behind a loadbalancer you have to configure the storage volume for the images.

**Heads up**: We now require CraftCMS >= 3.5.0 since this releaase

Best regards,
Felix
