### ISSUE TITLE
Can't get images as assets

### ISSUE THREAD

**Issue by boboldehampsink** [codemonauts/craft-instagram-feed#55]
The only output i'm seeing is this:

```
  [0]=>
  array(6) {
    ["src"]=>
    string(310) "https://scontent-ams4-1.cdninstagram.com/v/t51.2885-15/sh0.08/e35/c240.0.959.959a/s640x640/214449600_895916131268755_8566997712571008720_n.jpg?_nc_ht=scontent-ams4-1.cdninstagram.com&_nc_cat=107&_nc_ohc=pzMYh0THixEAX8zyhOE&edm=ABZsPhsBAAAA&ccb=7-4&oh=68bb1a8d386dcf7727640bb85f806722&oe=60F8E6A7&_nc_sid=4efc9f"
    ["likes"]=>
    int(12)
    ["comments"]=>
    int(0)
    ["shortcode"]=>
    string(11) "CRLU2-BjLNb"
    ["timestamp"]=>
    int(1625985185)
    ["caption"]=>
    string(140) "Today the @3_nations_cup_mtb with @exventure_sports.
 Time for jumps 🤙

#exventure #3nationscup #mtbspaarnwoude #xco #uci #talentned #mtb"
  }
```

Could it be that instagram's structure has changed once again?

**Comment by fleaz** [comment]
Hey,

this looks like the structure our plugin generates internaly for your feed and because you have valid data in your array, apparently our plugin could reach Instagran and got the images.

But I would guess that you not integrated our plugin correctly in your template and therefore got this object dump. Could you please show me the snippet of your template where you included our plugin and got this result?

Also, from the keys in your plugin, I would assume that you are not using the latest version. Could you also check this please?

Best,
Felix

**Comment by boboldehampsink** [comment]
Ahh, I'm using 1.0.5. This is because 1.0.5 is the latest version that doesn't have PHP version constraints. I'm using PHP8. I need PHP8 support (at least in composer php version constraint) to be able to install the latest version.

**Comment by fleaz** [comment]
Oh, thanks for the heads up. Our requirement for the PHP version is indeed not PHP8 compatible. We will fix this asap, so you can use the latest Version :)

Nonetheless, could you show me a snippet of your template where you included our plugin? There is probably something wrong, which is why you get this object dump instead of an image URL.

**Comment by boboldehampsink** [comment]
Oh yeah I did the dump myself. I was just missing assets. Which is explained by the version :-)

**Comment by fleaz** [comment]
We will release a new version in a few hours which has a fixed PHP requirement in the composer.json, so you can upgrade to the latest release and then it should work :)

**Comment by boboldehampsink** [comment]
Thanks!

**Comment by fleaz** [comment]
Hey,
we just releases 1.1.8 with the required fix :)
