### ISSUE TITLE
Make proxy url configurable

### ISSUE THREAD

**Issue by lenvanessen** [codemonauts/craft-instagram-feed#56]
Can we make this url configurable so that we can set-up our own proxy?

Thanks!

**Comment by fleaz** [comment]
Hey,
no, this is currently not configurable. We decided on this because it's a fair bit of work to get a working proxy up and running.

Do you have a reason why you wan't to run your own instead of using the one* run by us?

Best,
Felix

* Free, Loadbalanced over multiple Accounts in two locations, Two layers of caching

**Comment by lenvanessen** [comment]
Hi Felix, 

Couldn't get it up and running with yours, the docs didn't mention how to get access. But just stumbled upon the pinned issue in Github, makes more sense now

**Comment by fleaz** [comment]
Oh okay, yeah you are right, the docs didn't mention how to get access. All the other people first checked the Github Issues and then saw the pinned issue and after I gave them their key, I pointed them to the docs. You are the first who started reading the docs on it's own :D  

But  thanks for the heads up, I will update the docs and mention the procedure on how to get access there :+1:
