### ISSUE TITLE
Add the ability to define your own proxy URL

### ISSUE THREAD

**Issue by dazy-erik** [codemonauts/craft-instagram-feed#58]
Thank you for a great plugin.

We are running into the issue with our Live-server being blocked by instagram, but our internal server IP isn't. It would be great to have the option to configure your own proxy URL, instead of having put the burden on you.

Thanks,
Erik

**Comment by fleaz** [comment]
Hey Erik,

you are not the first to ask for this, but currently we decided to not make this configurable because running a proxy is quite a bit of work, and we are concerned that making this configurable would also create a lot of unnecessary support requests eating our time which would be better invested in our big proxy infrastructure so it would benefit all users.

tl,dr: Just use ours :)

Best,
Felix
