### ISSUE TITLE
The last posts are not displayed in feed

### ISSUE THREAD

**Issue by thomasbendl** [codemonauts/craft-instagram-feed#65]
The plugin does not fetch the latest Instagram posts after the Craft CMS data cache is cleared. The latest Insta Posts in feed are 12 hours old, so the 6 hour update check should actually work. 
images are stored in storage directory

**Where is it happening?**
  * [ x] On a server php 7.4.3
  * [x ] Local dev environment 8.0.24

**What are you requesting:**
Username: pichlertraupmann

```php
<?php

return [
    'useProxy' => true,
    'proxyKey' => '',
    'useGuzzle' => true,
];

```

**Software versions:**
Plugin Version: 1.2.0
PHP Version local: 8.0.24
PHP Version Server: 7.4.3
CraftCMS Version: Craft Pro 3.7.59

**Comment by fleaz** [comment]
Hey Thomas,
I'm really sorry for the late reply, I somehow missed the notification.

From the creation date of you issue I can correlate this to a week where we had some problems with the proxy and the update times for the accounts where pretty high (sometimes multiple days). Because everything is back to normal now, I would assume everything is fine for you too now and this  issue has been resolved? 

Best, 
Felix
