### ISSUE TITLE
Requesting data from a hashtag doesn't work

### ISSUE THREAD

**Issue by pwtStefanPeters** [codemonauts/craft-instagram-feed#66]
**Describe the bug:**

Requesting images of a hashtag is not working. I get back an empty array in twig. Requesting the images of a profile page does work.

**Steps to reproduce:**
1. Request the data from a profile page: `craft.instagram.getFeed('perfectwebteam')`
2. Request the data from a hashtag: `craft.instagram.getFeed('#golfen')`

**Where is it happening?**
  Local dev environment

**What are you requesting:**
Username: perfectwebteam
Hashtag: golfen

**Config file:**

```php
<?php
return [
    'timeout' => 10,
    'useProxy' => true,
    'proxyKey' => '***',
    'useGuzzle' => true,
    'useVolume' => false,
    'volume' => 'instagram'
];
?>

```

**Software versions:**
Plugin Version: 1.2.0
PHP Version: 8.1.13
CraftCMS Version: 3.7.59

**Comment by fleaz** [comment]
Hey, 
I see you are using our proxy. My first guess would be that you are hitting [this problem](https://plugins.codemonauts.com/plugins/instagramfeed/Proxy.html#help-it-s-not-working) because you requested the hashtag for the first time.

Can you confirm this? Because I can see the cached data for the hashtag in the proxy, so I assume this was just a timing issue

**Comment by sanderpotjer** [comment]
@fleaz thanks, we can confirm images are indeed now visible.
